import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import Footer from "./Components/Contact";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <header className="sticky top-0 z-50">

          <Header />

        </header>


        {children}


        <footer className="bg-white text-black px-6 py-8 lg:px-36 lg:py-16">
          <div className="container mx-auto text-center flex flex-col md:flex-row gap-6 md:justify-between">
            <p className="mb-4 md:mb-0">&copy; 2024 Eventi. Tous droits réservés.</p>
            <div className="flex flex-col md:flex-row space-y-4 md:space-y-0 md:space-x-4">
              <a href="#" className="hover:underline">Politique de confidentialité</a>
              <a href="#" className="hover:underline">Termes & Conditions</a>
            </div>
          </div>
        </footer>



      </body>
    </html >
  );
}
